main:
  params: [input]
  steps:
    - init:
        assign:
          - app_url: "https://www.synervion.com"
          - secret_token: "1234567"
          - auth_header: ${"Bearer " + secret_token}
          - topic: ${input.topic}
          - draft_a: null
          - draft_b: null
          - draft_c: null
          - candidates: []
          - scored_candidates: []

    # 1. RESEARCH PHASE
    - perform_research:
        call: http.post
        args:
          url: ${app_url + "/api/agent/router?action=research"}
          headers:
            Authorization: ${auth_header}
          body:
            topic: ${topic}
        result: research_data

    # 2. PARALLEL DRAFTING (The "Best-of-3" Strategy)
    - generate_candidates:
        parallel:
          shared: [draft_a, draft_b, draft_c]
          branches:
            - analyst:
                steps:
                  - run_analyst:
                      call: http.post
                      args:
                        url: ${app_url + "/api/agent/router?action=draft"}
                        headers:
                          Authorization: ${auth_header}
                        body:
                          topic: ${topic}
                          context: ${research_data.body.context}
                          angle: "Angle: Data-Driven Analyst (Focus on stats, biochemistry, and papers)"
                      result: res_a
                  - save_a:
                      assign:
                        - draft_a:
                            draft: ${res_a.body.draft}
                            angle: "Analyst"
            
            - storyteller:
                steps:
                  - run_storyteller:
                      call: http.post
                      args:
                        url: ${app_url + "/api/agent/router?action=draft"}
                        headers:
                          Authorization: ${auth_header}
                        body:
                          topic: ${topic}
                          context: ${research_data.body.context}
                          angle: "Angle: Master Storyteller (Focus on narrative, suspense, and human element)"
                      result: res_b
                  - save_b:
                      assign:
                        - draft_b:
                            draft: ${res_b.body.draft}
                            angle: "Storyteller"

            - skeptic:
                steps:
                  - run_skeptic:
                      call: http.post
                      args:
                        url: ${app_url + "/api/agent/router?action=draft"}
                        headers:
                          Authorization: ${auth_header}
                        body:
                          topic: ${topic}
                          context: ${research_data.body.context}
                          angle: "Angle: Contrarian/Myth-Buster (Focus on challenging common assumptions)"
                      result: res_c
                  - save_c:
                      assign:
                        - draft_c:
                            draft: ${res_c.body.draft}
                            angle: "Skeptic"

    - aggregate_candidates:
        assign:
          - candidates: [${draft_a}, ${draft_b}, ${draft_c}]

    # 3. CRITIQUE PHASE (Also Parallel for speed)
    # 3. CRITIQUE PHASE (Serial Loop for Safety)
    - score_candidates:
        for:
          value: candidate
          in: ${candidates}
          steps:
            - critique_call:
                call: http.post
                args:
                  url: ${app_url + "/api/agent/router?action=critique"}
                  headers:
                    Authorization: ${auth_header}
                  body:
                    topic: ${topic}
                    draft: ${candidate.draft}
                result: critique_res
            - create_score_item:
                assign:
                  - score_item:
                      draft: ${candidate.draft}
                      angle: ${candidate.angle}
                      score: ${critique_res.body.score}
                      report: ${critique_res.body.report}
            - save_scored:
                assign:
                  - scored_candidates: ${list.concat(scored_candidates, [score_item])}

    # 4. SELECTION PHASE
    - select_winner:
        call: http.post
        args:
          url: ${app_url + "/api/agent/router?action=select-winner"}
          headers:
            Authorization: ${auth_header}
          body:
            candidates: ${scored_candidates}
        result: winner_res
    
    - assign_winner:
        assign:
          - winner: ${winner_res.body.winner}

    # 5. POLISH PHASE (Optional One-Shot)
    - check_polish:
        switch:
          - condition: ${winner.score < 95}
            steps:
              - refine_winner:
                  call: http.post
                  args:
                    url: ${app_url + "/api/agent/router?action=refine"}
                    headers:
                      Authorization: ${auth_header}
                    body:
                      topic: ${topic}
                      draft: ${winner.draft}
                      critique: ${winner.report}
                      context: ${research_data.body.context}
                  result: refined_res
              - update_winner:
                  assign:
                    - winner.draft: ${refined_res.body.refined_draft}
                    - winner.score: 99 # Assumed improved

    # 6. VISUALS & DELIVERY
    - generate_visuals:
        call: http.post
        args:
          url: ${app_url + "/api/agent/router?action=visual"}
          headers:
            Authorization: ${auth_header}
          body:
            draft: ${winner.draft}
        result: visual_res

    - send_email:
        call: http.post
        args:
          url: ${app_url + "/api/agent/router?action=delivery"}
          headers:
            Authorization: ${auth_header}
          body:
            topic: ${topic}
            final_draft: ${winner.draft}
            image_url: ${visual_res.body.image_url}
            qa_report: ${winner.report}
        result: delivery_res

    - return_final:
        return:
          status: "success"
          published_topic: ${topic}
          final_score: ${winner.score}
